### ISSUE TITLE
Find and install a theme

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-gbaqua#1]
URL: gbaqua.editllc.com/wp-admin

I already shared the creds with you via lastpass.

This is his current live URL:
http://gbaqua.com/

Who is the typical user of your website?
People who buy feed/food for their shrimp

Link to meeting  notes:
https://drive.google.com/open?id=1VcCUJrH4NZUCy9pV3j4tSHG0AGHuwqDOMZLbG5Wv4ow

due: 10-20-15 3p

**Comment by rodneystrong** [comment]
I know you're a pro at this so if you want to do this the hardcore way (creating your own theme and child theme and coding everything from scratch) then go ahead, but you'll still need to do it all on the MT server so that gbaqua.editllc.com is updated and the client can see progress.

**Comment by purplyrocky** [comment]
I didn't get the username in the creds you shared

**Comment by rodneystrong** [comment]
*RAAAWR   fail lastpass. 
This is like the 3rd time that's happened when i've created these new sites on WP. 
Just updated the creds, but username is edit-gbaqua
sorry about that
