### ISSUE TITLE
Create a child theme

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-gbaqua#2]
Use this plugin to create a child theme: https://wordpress.org/plugins/child-theme-configurator/

Comment here if you're unsure how to install a plugin; but with some googling and intuition I think you'll figure it out.

due: 10-20-15 4p

**Comment by rodneystrong** [comment]
Again, same story: 

I know you're a pro at this so if you want to do this the hardcore way (creating your own theme and child theme and coding everything from scratch) then go ahead, but you'll still need to do it all on the MT server so that gbaqua.editllc.com is updated and the client can see progress

**Comment by AaronAguilar** [comment]
Here's what's been done now - 
http://gbaqua.editllc.com/

**Comment by rodneystrong** [comment]
heeeeey not bad.
